test_config:
  sampling_strategy: "grid"
  x_range: [-0.015, 0.00, 0.01]
  y_range: [-0.015, 0.00, 0.01]
  z_range: [0.03, 0.00, -0.001]
  roll_angles: [-45.0, 0.0, 50.0]
  pitch_angles: [45.0, 0, -5]
  yaw_angles: [-15.0, 0, 100]
  random_seed: 42
  axis_combinations:
    - ["x"]
    - ["y"]
    - ["z"]
    - ["roll"]
    - ["pitch"]
    - ["yaw"]
    - ["x", "y"]
  approach_settings:               # Settings for the vertical approach
    use_vertical_approach: true    # Enable/disable vertical approach
    approach_height: 0.1           # Height above object in meters
    approach_velocity: 0.3         # Velocity for approach
    approach_acceleration: 0.3     # Acceleration for approach